config/routes.rb
Rails.application.routes.draw do
  root to: 'rentals#index'
  resources :rentals, except: :show do
    resources :rental_tracked_positions, except: :show do
      collection do
        get :import_csv
        post :do_import_csv
        delete :destroy_all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
  has_many :rental_tracked_positions, dependent: :restrict_with_error

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :total_distance, numericality: { greater_than_or_equal_to: 0.0 }

  before_validation :set_total_distance_before_validation
  # this is a habit I took: add the callback's name after the method's name.
  # This becomes pretty useful when you have a model with quite a lot of methods defined

  def erase_all_tracked_positions
    # specific method to destroy several positions but compute the total_distance only once
    transaction do
      self.rental_tracked_positions.each do |rtp|
        rtp.skip_compute_total_distance = true
        rtp.destroy
      end
      self.set_computed_total_distance
      self.save
    end
  end

  def set_computed_total_distance
    self.total_distance = compute_total_distance
  end

  def compute_total_distance
    total_distance_in_km = 0.0
    positions = self.rental_tracked_positions.order(tracked_at: :asc)
    positions.each_with_index do |position, i|
      next_position = positions[i+1]
      if next_position
        current_pos_arr = [position.latitude, position.longitude]
        next_pos_arr = [next_position.latitude, next_position.longitude]
        total_distance_in_km += Geocoder::Calculations.distance_between(current_pos_arr, next_pos_arr, units: :km)
      end
    end
    total_distance_in_km
  end

  protected

  def set_total_distance_before_validation
    self.total_distance ||= 0.0
  end
end

app/models/rental_tracked_position.rb
class RentalTrackedPosition < ApplicationRecord
  attr_accessor :skip_compute_total_distance
  # non-persisted attribute to be able to skip the compute_total_distance call when creating/updating/deleting several
  # RentalTrackedPosition records at once and only call it once when all the records are created/updated/deleted

  belongs_to :rental

  scope :ordered, -> { order(tracked_at: :desc) }

  validates :rental, presence: true
  validates :tracked_at, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :tracked_at, uniqueness: { scope: [:rental_id, :latitude, :longitude] } # avoid duplicates
  # FYI: your CSV file contains several records for the same timestamp, some are total duplicates,
  # others have different lat/long for the same timestamp

  after_save :compute_total_distance_after_save_or_destroy
  after_destroy :compute_total_distance_after_save_or_destroy

  protected

  def compute_total_distance_after_save_or_destroy
    return if @skip_compute_total_distance
    self.rental.set_computed_total_distance
    self.rental.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rental_tracked_positions_controller.rb
require 'rental_tracked_position_csv_importer' # Yes, I prefer to require instead of autoloading it (Why would all the other files could access this Class?)

class RentalTrackedPositionsController < ApplicationController
  before_action :set_rental
  before_action :set_rental_tracked_position, only: [:edit, :update, :destroy]

  def import_csv
  end

  def do_import_csv
    # I know I could have used the same `import_csv` action and handle the GET and POST requests, but it feels messy
    importer = RentalTrackedPositionCsvImporter.new(@rental, params[:csv_file])
    importer.execute
    if importer.errors.present?
      flash[:danger] = importer.errors
    else
      flash[:success] = 'Successfully imported!'
    end
    redirect_to rental_rental_tracked_positions_path(@rental)
  end

  def index
    @rental_tracked_positions = @rental.rental_tracked_positions.ordered
  end

  def new
    @rental_tracked_position = @rental.rental_tracked_positions.new
  end

  def create
    @rental_tracked_position = @rental.rental_tracked_positions.new(rental_tracked_position_params)
    if @rental_tracked_position.save
      redirect_to rental_rental_tracked_positions_path(@rental), flash: { success: 'Success!' }
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rental_tracked_position.update_attributes(rental_tracked_position_params)
      redirect_to rental_rental_tracked_positions_path(@rental), flash: { success: 'Success!' }
    else
      render 'edit'
    end
  end

  def destroy
    if @rental_tracked_position.destroy
      redirect_to rental_rental_tracked_positions_path(@rental), flash: { success: 'Success!' }
    else
      render 'edit'
    end
  end

  def destroy_all
    @rental.erase_all_tracked_positions
    redirect_to rental_rental_tracked_positions_path(@rental), flash: { success: 'Successfully deleted all positions related to this rental' }
  end

  protected

  def rental_tracked_position_params
    params.require(:rental_tracked_position).permit(:tracked_at, :latitude, :longitude)
  end

  def set_rental
    @rental = Rental.find(params[:rental_id])
  end

  def set_rental_tracked_position
    @rental_tracked_position = @rental.rental_tracked_positions.find(params[:id])
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:edit, :update, :destroy]

  def index
    @rentals = Rental.default_scoped
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    if @rental.save
      redirect_to rentals_path, flash: { success: 'Success!' }
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rental.update_attributes(rental_params)
      redirect_to rentals_path, flash: { success: 'Success!' }
    else
      render 'edit'
    end
  end

  def destroy
    if @rental.destroy
      redirect_to rentals_path, flash: { success: 'Success!' }
    else
      render 'edit'
    end
  end

  protected

  def rental_params
    params.require(:rental).permit(:name)
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_resource_errors(resource)
    return if resource.errors.blank?
    content_tag(:div, class: 'alert alert-danger') do
      resource.errors.full_messages.join('<br/>').html_safe
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KoolicarTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %br
      - if flash.present?
        - flash.each do |key, text|
          %div.alert.alert-dismissible{ class: "alert-#{key}" }
            %a.close{ href: '#', data: { dismiss: 'alert' } } &times;
            = Array.wrap(text).join('<br/>').html_safe
        %br

      = yield

app/views/rental_tracked_positions/_form.html.haml
= display_resource_errors(@rental_tracked_position)

= form_for [@rental, @rental_tracked_position] do |f|
  .form-group
    = f.label :rental
    = f.text_field :rental, value: @rental.name, class: 'form-control',disabled: true

  .form-group
    = f.label :tracked_at
    = f.datetime_field :tracked_at, class: 'form-control', placeholder: RentalTrackedPosition.human_attribute_name(:tracked_at)

  .form-group
    = f.label :latitude
    = f.number_field :latitude, step: 'any', class: 'form-control'

  .form-group
    = f.label :longitude
    = f.number_field :longitude, step: 'any', class: 'form-control'

  .form-group
    = f.submit 'Save', class: 'btn btn-secondary'
    = link_to rental_rental_tracked_positions_path(@rental) do
      .btn.btn-secondary= 'Cancel'
    - if @rental_tracked_position.persisted?
      = link_to rental_rental_tracked_position_path(@rental, @rental_tracked_position), method: :delete do
        .btn.btn-secondary= 'Delete'

app/views/rental_tracked_positions/edit.html.haml
%h1= "#{Rental.model_name.human} '#{@rental.name}': #{RentalTrackedPosition.model_name.human} ##{@rental_tracked_position.id}"

= render 'form'

app/views/rental_tracked_positions/import_csv.html.haml
.row
  .col-md-9
    %h1= 'Import positions from CSV file'
  .col-md-3
    = link_to rental_rental_tracked_positions_path(@rental) do
      .btn.btn-secondary= 'Back'

= form_tag do_import_csv_rental_rental_tracked_positions_path(@rental), multipart: true do
  .form-group
    = label_tag 'csv_file', 'CSV file'
    = file_field_tag 'csv_file', class: 'form-control'

  .form-group
    = submit_tag 'Send', class: 'btn btn-secondary'
    = link_to rental_rental_tracked_positions_path(@rental) do
      .btn.btn-secondary= 'Cancel'

app/views/rental_tracked_positions/index.html.haml
%h1= "#{Rental.model_name.human} '#{@rental.name}': #{RentalTrackedPosition.model_name.human.pluralize}"

.row{ style: 'text-align: center;' }
  = link_to edit_rental_path(@rental) do
    .btn.btn-secondary= 'Back'
  = link_to new_rental_rental_tracked_position_path(@rental) do
    .btn.btn-secondary= 'New tracked position'
  = link_to import_csv_rental_rental_tracked_positions_path(@rental) do
    .btn.btn-secondary= 'Import positions from CSV'
  = link_to destroy_all_rental_rental_tracked_positions_path(@rental), method: :delete, data: { confirm: 'Are you sure?' } do
    .btn.btn-secondary= 'Destroy all positions'

.row
  Total distance:
  = @rental.total_distance.round(3)
  km

%table.table.table-hover.table-bordered
  %thead
    %tr
      %th= 'id'
      %th{ style: 'width: 60%' }= RentalTrackedPosition.human_attribute_name(:tracked_at)
      %th= RentalTrackedPosition.human_attribute_name(:latitude)
      %th= RentalTrackedPosition.human_attribute_name(:longitude)
      %th{ style: 'width: 20%' }= 'Actions'
  %tbody
    - @rental_tracked_positions.each do |rental_tracked_position|
      %tr
        %td= rental_tracked_position.id
        %td= l(rental_tracked_position.tracked_at)
        %td{ style: 'text-align: right;' }= rental_tracked_position.latitude
        %td{ style: 'text-align: right;' }= rental_tracked_position.longitude
        %td{ style: 'text-align: center;' }
          = link_to edit_rental_rental_tracked_position_path(@rental, rental_tracked_position) do
            .btn.btn-secondary= 'Edit'
          = link_to rental_rental_tracked_position_path(@rental, rental_tracked_position), method: :delete, data: { confirm: 'Are you sure?' } do
            .btn.btn-secondary= 'Delete'

app/views/rental_tracked_positions/new.html.haml
%h1= RentalTrackedPosition.model_name.human

= render 'form'

app/views/rentals/_form.html.haml
= display_resource_errors(@rental)

= form_for @rental do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: Rental.human_attribute_name(:name)

  .form-group
    = f.submit 'Save', class: 'btn btn-secondary'
    = link_to rentals_path do
      .btn.btn-secondary= 'Cancel'
    - if @rental.persisted?
      = link_to rental_path(@rental), method: :delete do
        .btn.btn-secondary= 'Delete'

app/views/rentals/edit.html.haml
.row
  .col-md-9
    %h1= "#{Rental.model_name.human}: #{@rental.name}"
  .col-md-3
    = link_to rental_rental_tracked_positions_path(@rental) do
      .btn.btn-secondary= 'View tracked positions'

= render 'form'

app/views/rentals/index.html.haml
.row
  .col-md-10
    %h1= Rental.model_name.human.pluralize
  .col-md-2
    = link_to new_rental_path do
      .btn.btn-secondary= 'New'

%table.table.table-hover.table-bordered
  %thead
    %tr
      %th= 'id'
      %th{ style: 'width: 50%' }= Rental.human_attribute_name(:name)
      %th= 'Tracked positions count'
      %th= 'Total distance (km)'
      %th{ style: 'width: 20%' }= 'Actions'
  %tbody
    - @rentals.each do |rental|
      %tr
        %td= rental.id
        %td= rental.name
        %td= rental.rental_tracked_positions.count
        %td{ style: 'text-align: right;' }= rental.total_distance.round(3)
        %td{ style: 'text-align: center;' }
          = link_to edit_rental_path(rental) do
            .btn.btn-secondary= 'Edit'
          = link_to(rental_path(rental), method: :delete, data: { confirm: 'Are you sure?' }) do
            .btn.btn-secondary= 'Delete'

app/views/rentals/new.html.haml
%h1= Rental.model_name.human

= render 'form'